{% set version = "0.13.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-modules
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/modules_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/modules/modules_{{ version }}.tar.gz
  sha256: 553b42f26627db265de5279f93f4b1f9d141d67e51c8f56b86e86fd6a5b7c7fc

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('modules')"           # [not win]
    - "\"%R%\" -e \"library('modules')\""  # [win]

about:
  home: https://github.com/wahani/modules
  license: MIT
  summary: Provides modules as an organizational unit for source code. Modules enforce to be more rigorous when defining dependencies and have a local search path. They can be used as a sub unit within packages or in scripts.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
